dist: trusty

git:
  depth: 1

language: cpp

compiler:
 - gcc

branches:
  only:
    - master

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

before_install:
 - pwd
 - sudo apt-get update -qq
 - sudo apt-get install -qq libsfml-dev

before_script:
 - mkdir build
 - cd build
 - cmake ..

script:
 - make -j2

notifications:
  email: false